// Instruments
export const instruments = [{
    id: 'Piano',
    name: 'Piano',
  }, {
    id: 'Trumpet',
    name: 'Trumpet',
  }, {
    id: 'Trombone',
    name: 'Trombone',
  }, {
    id: 'Violin',
    name: 'Violin',
  }, {
    id: 'Djembe',
    name: 'Djembe',
  }, {
    id: 'Triangle',
    name: 'Triangle',
  }, {
    id: 'Drums',
    name: 'Drums',
  }, {
    id: 'Cymbals',
    name: 'Cymbals',
  }, {
    id: 'Flute',
    name: 'Flute',
  }, {
    id: 'Flusdfgte',
    name: 'Flsdfute',
  }, {
    id: 'Flsdfsdfute',
    name: 'Flsdfsdfute',
  }, {
    id: 'Fludsasddsdsfsdte',
    name: 'Fldsfsdfute',
  }, {
    id: 'Flutdfasdsde',
    name: 'Flusdfsdfte',
  }, {
    id: 'Flsafdussaddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsaddussaddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsaduffssaddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsadudssaddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsadussasdfsddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsadusfsaddfsdte',
    name: 'Flutesdfsdf',
  }, {
    id: 'Flsadusssdfsdaddfsdte',
    name: 'Flutesdfsdf',
  }
];

// Genres
export const genres = [{
    id: 'Blues',
    name: 'Blues',
  }, {
    id: 'Classical',
    name: 'Classical',
  }, {
    id: 'Country',
    name: 'Country',
  }, {
    id: 'Electronic',
    name: 'Electronic',
  }, {
    id: 'Folk',
    name: 'Folk',
  }, {
    id: 'Funk',
    name: 'Funk',
  }, {
    id: 'Hip Hop',
    name: 'Hip Hop',
  }, {
    id: 'Jazz',
    name: 'Jazz',
  }, {
    id: 'Latin',
    name: 'Latin',
  }, {
    id: 'Metal',
    name: 'Metal',
  }, {
    id: 'Pop',
    name: 'Pop',
  }, {
    id: 'R&B',
    name: 'R&B',
  }, {
    id: 'Reggae',
    name: 'Reggae',
  }, {
    id: 'Rock',
    name: 'Rock',
  }, {
    id: 'Soul',
    name: 'Soul',
  },
];
// African
// Blues
// Classical
// Country
// Electronic
// Folk
// Funk
// Hip Hop
// Jazz
// Latin
// Metal
// Pop
// R&B
// Reggae
// Rock
// Soul
